// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogsRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lines                int64    `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`
	Follow               bool     `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	PodName              string   `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Previous             bool     `protobuf:"varint,5,opt,name=previous,proto3" json:"previous,omitempty"`
	Container            string   `protobuf:"bytes,6,opt,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogsRequest) Reset()         { *m = LogsRequest{} }
func (m *LogsRequest) String() string { return proto.CompactTextString(m) }
func (*LogsRequest) ProtoMessage()    {}
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *LogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogsRequest.Unmarshal(m, b)
}
func (m *LogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogsRequest.Marshal(b, m, deterministic)
}
func (m *LogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogsRequest.Merge(m, src)
}
func (m *LogsRequest) XXX_Size() int {
	return xxx_messageInfo_LogsRequest.Size(m)
}
func (m *LogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogsRequest proto.InternalMessageInfo

func (m *LogsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogsRequest) GetLines() int64 {
	if m != nil {
		return m.Lines
	}
	return 0
}

func (m *LogsRequest) GetFollow() bool {
	if m != nil {
		return m.Follow
	}
	return false
}

func (m *LogsRequest) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *LogsRequest) GetPrevious() bool {
	if m != nil {
		return m.Previous
	}
	return false
}

func (m *LogsRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

type LogsResponse struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogsResponse) Reset()         { *m = LogsResponse{} }
func (m *LogsResponse) String() string { return proto.CompactTextString(m) }
func (*LogsResponse) ProtoMessage()    {}
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *LogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogsResponse.Unmarshal(m, b)
}
func (m *LogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogsResponse.Marshal(b, m, deterministic)
}
func (m *LogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogsResponse.Merge(m, src)
}
func (m *LogsResponse) XXX_Size() int {
	return xxx_messageInfo_LogsResponse.Size(m)
}
func (m *LogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogsResponse proto.InternalMessageInfo

func (m *LogsResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*LogsRequest)(nil), "app.LogsRequest")
	proto.RegisterType((*LogsResponse)(nil), "app.LogsResponse")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4a, 0xc6, 0x30,
	0x10, 0xc4, 0x89, 0xe9, 0x57, 0xdb, 0xd5, 0x83, 0x2e, 0x22, 0xf1, 0xc3, 0x43, 0xe9, 0xa9, 0x17,
	0x3f, 0x44, 0x7d, 0x01, 0xef, 0xe2, 0x21, 0x2f, 0x20, 0xd1, 0xae, 0x52, 0xa8, 0xd9, 0xb5, 0x49,
	0xd5, 0x07, 0xf2, 0x41, 0x25, 0xa9, 0x7f, 0x7a, 0xdb, 0x19, 0x32, 0x3f, 0x66, 0x02, 0xb5, 0x13,
	0xd9, 0xc9, 0xc4, 0x91, 0x51, 0x3b, 0x91, 0xf6, 0x4b, 0xc1, 0xc1, 0x1d, 0xbf, 0x04, 0x4b, 0x6f,
	0x33, 0x85, 0x88, 0x08, 0x85, 0x77, 0xaf, 0x64, 0x54, 0xa3, 0xba, 0xda, 0xe6, 0x1b, 0x4f, 0x60,
	0x33, 0x0e, 0x9e, 0x82, 0xd9, 0x6b, 0x54, 0xa7, 0xed, 0x22, 0xf0, 0x14, 0xca, 0x67, 0x1e, 0x47,
	0xfe, 0x30, 0xba, 0x51, 0x5d, 0x65, 0x7f, 0x14, 0x9e, 0x41, 0x25, 0xdc, 0x3f, 0x64, 0x4a, 0x91,
	0x29, 0xfb, 0xc2, 0xfd, 0x7d, 0x02, 0x6d, 0xa1, 0x92, 0x89, 0xde, 0x07, 0x9e, 0x83, 0xd9, 0xe4,
	0xd0, 0x9f, 0xc6, 0x73, 0xa8, 0x9f, 0xd8, 0x47, 0x37, 0x78, 0x9a, 0x4c, 0x99, 0x73, 0xff, 0x46,
	0xdb, 0xc2, 0xe1, 0xd2, 0x32, 0x08, 0xfb, 0x40, 0xa9, 0x66, 0xa4, 0xcf, 0xf8, 0x5b, 0x33, 0xdd,
	0x57, 0x37, 0xa0, 0x6f, 0x45, 0xf0, 0x02, 0x8a, 0xf4, 0x14, 0x8f, 0x76, 0x69, 0xea, 0x6a, 0xdb,
	0xf6, 0x78, 0xe5, 0x2c, 0x9c, 0x4b, 0xf5, 0x58, 0xe6, 0xcf, 0xb8, 0xfe, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0xc9, 0xe1, 0x0d, 0x39, 0x19, 0x01, 0x00, 0x00,
}
